### ISSUE TITLE
Create a new enum in pkgEnum called eGameDifficulty

### ISSUE THREAD

**Issue by jvillemare** [jvillemare/CISC181-Sudoku#12]
The enum should have three values, EASY, MEDIUM and HARD.  The enum should have an attribute associated with it named iDifficultyValue.

**Comment by EvanYang0527** [comment]
Fixed in https://github.com/jvillemare/CISC181-Sudoku/commit/8e71f5027a11aaed4b5b517e062b6e631c46f370
