### ISSUE TITLE
Create a map in the eGameDifficulty

### ISSUE THREAD

**Issue by jvillemare** [jvillemare/CISC181-Sudoku#13]
Check out this page to show you how to return an enum with a parameter:
https://stackoverflow.com/questions/1080904/how-can-i-lookup-a-java-enum-from-its-string-value

Check out ‘Day’ enum.  Note public static Day get(String abbreviation).  This method allows the user to pass in an abbreviation and be returned a specific enum that’s been mapped in the ‘lookup’ map. 

![image](https://user-images.githubusercontent.com/6162516/56686607-5519cc80-66a2-11e9-84bc-73aa3e45d09f.png)

**Comment by jvillemare** [comment]
After the enum is created, add a new attribute to the Sudoku class, named eGameDifficulty.

**Comment by EvanYang0527** [comment]
Fixed in https://github.com/jvillemare/CISC181-Sudoku/commit/8e71f5027a11aaed4b5b517e062b6e631c46f370
