### ISSUE TITLE
New two-arg public Constructor for Sudoku

### ISSUE THREAD

**Issue by jvillemare** [jvillemare/CISC181-Sudoku#15]
Create a new public two-arg constructor for Sudoku, passing in the size and the difficulty.

The two arg-constructor should call the Sudoku(int) constructor and then set the difficulty that’s passed as a parameter

**Comment by 0Aris0** [comment]
Fixed in https://github.com/jvillemare/CISC181-Sudoku/commit/b03b11d05ad397d910b64630f60d8588d35f66a0
