### ISSUE TITLE
Create a new method setRemainingCells()

### ISSUE THREAD

**Issue by jvillemare** [jvillemare/CISC181-Sudoku#16]
Similar to SetCells(), this method will set lstRemainingValidValues.

**Comment by jvillemare** [comment]
*According to the Javadoc:*

Set lstRemainingValidValues, don't shuffle. Pretty close to SetCells()

**Comment by EvanYang0527** [comment]
Fixed in https://github.com/jvillemare/CISC181-Sudoku/commit/80d223d7af8afc0b610aa2eed72d2dd3642cdf2c
