### ISSUE TITLE
Create new method possibleValuesMultiplier()

### ISSUE THREAD

**Issue by jvillemare** [jvillemare/CISC181-Sudoku#17]
Read the JavaDoc for specifics.

**Comment by jvillemare** [comment]
*According to the Javadoc:* 

Will return back an integer calculated from the possible remaining values Steps... Step 1: Generate the Sudoku (using constructor), fill entire puzzle, set the difficulty Step 2: Randomly set a cell to zero Step 3: set lstRemainingValidValues with remaining possible values Step 4: calculate PossibleValuesMultipler. Iterate through the 'cells' hashmap, multiplying the lstRemainingValues.Size for each cell. If the multiplier is greater than the MAX_VALUE for an Integer, return the Integer.MAX_VALUE Step 5: if the puzzle still doesn't meet the required difficulty, go to step 2

Parameters:
cells -

**Comment by paultownshend** [comment]
Fixed in https://github.com/jvillemare/CISC181-Sudoku/commit/967bf1c8cda68ac5789b6f2ea01cd233a84d67bd
