### ISSUE TITLE
Create new method isDifficultyMet(int)

### ISSUE THREAD

**Issue by jvillemare** [jvillemare/CISC181-Sudoku#18]
This method will return a Boolean if the given possible values meets the game’s difficulty.

**Comment by jvillemare** [comment]
*According to professor:*

**Parameters:**
eGD - given
iPossibleValues - ...
Returns: ...

We may need more information. I'm contacting him.

**Comment by YisiYin** [comment]
Fixed in https://github.com/jvillemare/CISC181-Sudoku/commit/e34cf93624b1d4a446507f8c2fc463bd32c056f0
